import {useEffect,useMemo,useRef,useState} from 'react'
import {ArrowDownUp, ArrowLeft, ArrowRight, Bookmark, Check, ChevronRight, Gauge, Heart, Info, LocateFixed, Navigation2, Route, Search, Settings2, ShieldAlert, Volume2} from 'lucide-react'
import dataJson from './data/demo.json'
import {Button} from '@/components/ui/button'
import {Badge} from '@/components/ui/badge'
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card'
import {Input} from '@/components/ui/input'
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog'
import {calcFuel,cn,km,krw,totalCost,travelTime} from '@/lib/utils'

type Food={name:string,category:string,price:number,highlight?:boolean}
type Stop={id:string,name:string,road:string,direction:string,km:number,facilities:string[],note:string,foods:Food[]}
type RouteData={id:string,type:'fast'|'cheap'|'food',label:string,subtitle:string,road:string,distance:number,duration:number,toll:number,stops:string[],tint:string,points:number[][]}
type Journey={key:string,from:string,to:string,routes:RouteData[]}
type Dataset={stops:Record<string,Stop>,journeys:Journey[],facilityNames:Record<string,string>}
const DATA=dataJson as unknown as Dataset
const fuels={gasoline:'휘발유',diesel:'경유',lpg:'LPG',electric:'전기'} as const
type FuelType=keyof typeof fuels
type Prefs={journeyKey:string,routeId:string,category:string,facilities:string[],favorites:string[],fuel:FuelType,mileage:number,unitPrice:number,maxDetour:number,progress:number}
const defaults:Prefs={journeyKey:'서울-부산',routeId:'fast-busan',category:'전체',facilities:[],favorites:[],fuel:'gasoline',mileage:12,unitPrice:1700,maxDetour:40,progress:0}
function initialPrefs():Prefs {try{const raw=JSON.parse(localStorage.getItem('restway-v2')||'{}') as Partial<Prefs>;return {...defaults,...raw,facilities:Array.isArray(raw.facilities)?raw.facilities:[],favorites:Array.isArray(raw.favorites)?raw.favorites:[]}}catch{return defaults}}
const facilities=['fuel','family','baby','repair','sleep','ev']
const facilitySymbols:Record<string,string>={fuel:'주유',family:'가족화장실',baby:'수유실',repair:'정비',sleep:'휴식',ev:'전기차 충전'}
const icons:Record<string,string>={fuel:'⛽',family:'🚻',baby:'🍼',repair:'🔧',sleep:'🛏',ev:'⚡'}
const catNames=['전체','식사','간식','음료']
const routeLabels:Record<RouteData['type'],string>={fast:'시간 우선',cheap:'비용 우선',food:'먹거리 우선'}

function useNotice(){const [notice,setNotice]=useState('');const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);function notify(message:string){setNotice(message);if(timeout.current)clearTimeout(timeout.current);timeout.current=setTimeout(()=>setNotice(''),3500)}useEffect(()=>()=>{if(timeout.current)clearTimeout(timeout.current)},[]);return {notice,notify}}

export default function App(){
 const [prefs,setPrefs]=useState<Prefs>(initialPrefs)
 const [mode,setMode]=useState<'plan'|'drive'>('plan')
 const [queryFrom,setQueryFrom]=useState('서울')
 const [queryTo,setQueryTo]=useState('부산')
 const [foodSearch,setFoodSearch]=useState('')
 const [favOnly,setFavOnly]=useState(false)
 const [selectedStop,setSelectedStop]=useState<string|null>(null)
 const [settingsOpen,setSettingsOpen]=useState(false)
 const [gps,setGps]=useState<{lat:number,lon:number,accuracy:number}|null>(null)
 const [gpsError,setGpsError]=useState('')
 const [gpsOn,setGpsOn]=useState(false)
 const watcher=useRef<number|null>(null)
 const {notice,notify}=useNotice()
 const update=(patch:Partial<Prefs>)=>setPrefs(prev=>({...prev,...patch}))
 useEffect(()=>{try{localStorage.setItem('restway-v2',JSON.stringify(prefs))}catch{}},[prefs])
 useEffect(()=>{return ()=>{if(watcher.current!==null)navigator.geolocation?.clearWatch(watcher.current)}},[])
 const journey=DATA.journeys.find(j=>j.key===prefs.journeyKey)??DATA.journeys[0]
 const route=journey.routes.find(r=>r.id===prefs.routeId)??journey.routes[0]
 const fastest=journey.routes.find(r=>r.type==='fast')??journey.routes[0]
 const fuelCost=(r:RouteData)=>calcFuel(r.distance,prefs.mileage,prefs.unitPrice)
 const cost=(r:RouteData)=>totalCost(r.toll,fuelCost(r))
 const allStops=route.stops.map(id=>DATA.stops[id]).filter((stop):stop is Stop=>Boolean(stop))
 const matchingStops=useMemo(()=>allStops.filter(stop=>{
  const byCat=prefs.category==='전체'||stop.foods.some(f=>f.category===prefs.category)
  const byFacility=prefs.facilities.every(f=>stop.facilities.includes(f))
  const byKeyword=!foodSearch.trim()||[stop.name,...stop.foods.map(f=>f.name)].some(v=>v.toLowerCase().includes(foodSearch.trim().toLowerCase()))
  return byCat&&byFacility&&byKeyword&&(!favOnly||prefs.favorites.includes(stop.id))
 }),[allStops,prefs.category,prefs.facilities,prefs.favorites,foodSearch,favOnly])
 const pending=allStops.filter(s=>s.km>prefs.progress)
 const next=pending[0]??null
 const detail=selectedStop?DATA.stops[selectedStop]:null
 function selectJourney(j:Journey){update({journeyKey:j.key,routeId:j.routes[0].id,progress:0,category:'전체',facilities:[]});setQueryFrom(j.from);setQueryTo(j.to);setMode('plan')}
 function doSearch(){const found=DATA.journeys.find(j=>j.from===queryFrom.trim()&&j.to===queryTo.trim());if(!found){notify('현재는 서울 → 부산 / 강릉 예시 경로만 제공합니다. 실제 지명 검색은 API 연결이 필요합니다.');return}selectJourney(found);notify(`${found.from} → ${found.to} 경로를 불러왔습니다.`)}
 function toggleFacility(id:string){update({facilities:prefs.facilities.includes(id)?prefs.facilities.filter(x=>x!==id):[...prefs.facilities,id]})}
 function toggleFavorite(id:string){update({favorites:prefs.favorites.includes(id)?prefs.favorites.filter(x=>x!==id):[...prefs.favorites,id]})}
 function toggleGps(){if(watcher.current!==null){navigator.geolocation.clearWatch(watcher.current);watcher.current=null;setGpsOn(false);setGps(null);notify('위치 확인을 종료했습니다.');return}if(!navigator.geolocation){notify('위치 확인을 지원하지 않는 브라우저입니다.');return}setGpsError('');setGpsOn(true);watcher.current=navigator.geolocation.watchPosition(pos=>{setGps({lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy})},err=>{setGpsError(err.code===1?'위치 권한이 거부됐습니다. 브라우저 설정을 확인하세요.':'위치를 확인하지 못했습니다. HTTPS 또는 localhost에서 실행해 주세요.');setGpsOn(false);watcher.current=null},{enableHighAccuracy:true,maximumAge:10000,timeout:15000})}
 function voice(){if(!next){notify('남은 휴게소가 없습니다.');return}if(!('speechSynthesis'in window)){notify('이 브라우저는 음성 안내를 지원하지 않습니다.');return}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(`시연 안내입니다. 다음 휴게소는 ${next.name}, 약 ${Math.round(next.km-prefs.progress)}킬로미터 남았습니다.`);utterance.lang='ko-KR';utterance.rate=.93;window.speechSynthesis.speak(utterance)}
 return <div className="min-h-screen pb-12">
  <header className="stickybar"><div className="content-width flex h-[70px] items-center justify-between gap-4">
   <button className="flex items-center gap-2.5" onClick={()=>setMode('plan')} aria-label="쉼표 홈"><div className="brand-mark">쉼</div><div className="text-left"><strong className="block text-[16px] tracking-[-.06em]">쉼표</strong><span className="block text-[10px] text-muted-foreground tracking-[.07em]">RESTWAY</span></div></button>
   <nav className="hidden items-center gap-6 md:flex" aria-label="주요 메뉴"><button className={cn('text-sm',mode==='plan'?'font-semibold':'text-muted-foreground')} onClick={()=>setMode('plan')}>경로 탐색</button><button className={cn('text-sm',mode==='drive'?'font-semibold':'text-muted-foreground')} onClick={()=>setMode('drive')}>이동 중 모드</button></nav>
   <div className="flex gap-2"><Button variant="outline" size="icon" aria-label="차량 설정" onClick={()=>setSettingsOpen(true)}><Settings2/></Button><Button onClick={()=>setMode(mode==='plan'?'drive':'plan')} size="sm" className="h-10 px-3">{mode==='plan'?<><Navigation2/> 주행 모드</>:<><ArrowLeft/> 돌아가기</>}</Button></div>
  </div></header>
  {mode==='plan'?<main className="content-width pt-8 md:pt-12">
   <div className="mb-7 flex flex-wrap items-end justify-between gap-3"><div><div className="subhead mb-2">REST AREA GUIDE</div><h1 className="text-3xl font-bold tracking-[-.07em] md:text-[38px]">가는 길, 잘 쉬는 법.</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">길을 비교하고, 먹고 쉬어갈 곳까지 한 번에.</p></div><Badge variant="outline" className="h-7 bg-white">프로토타입 · 가상 경로</Badge></div>
   <Card className="mb-9"><CardContent className="p-4 md:p-5"><form onSubmit={e=>{e.preventDefault();doSearch()}} className="grid grid-cols-[1fr_auto_1fr] items-end gap-2 md:grid-cols-[1fr_auto_1fr_140px]">
    <label className="min-w-0"><span className="mb-1.5 block text-xs font-medium text-muted-foreground">출발지</span><Input value={queryFrom} onChange={e=>setQueryFrom(e.target.value)} aria-label="출발지"/></label>
    <Button type="button" variant="ghost" size="icon" aria-label="출발지 목적지 전환" onClick={()=>{setQueryFrom(queryTo);setQueryTo(queryFrom)}} className="mb-0 h-10"><ArrowDownUp/></Button>
    <label className="min-w-0"><span className="mb-1.5 block text-xs font-medium text-muted-foreground">목적지</span><Input value={queryTo} onChange={e=>setQueryTo(e.target.value)} aria-label="목적지"/></label>
    <Button type="submit" className="col-span-3 md:col-span-1"><Search/> 경로 보기</Button>
   </form><div className="mt-3 flex flex-wrap items-center gap-2"><span className="mr-1 text-xs text-muted-foreground">예시 경로</span>{DATA.journeys.map(j=><Button key={j.key} variant={journey.key===j.key?'secondary':'outline'} size="sm" onClick={()=>selectJourney(j)}>{j.from} → {j.to}</Button>)}</div></CardContent></Card>
   <section aria-labelledby="routes-title" className="mb-9"><div className="mb-3 flex items-end justify-between"><div><p className="subhead mb-1">COMPARE ROUTES</p><h2 id="routes-title" className="text-lg font-bold">어떤 길로 갈까요?</h2></div><span className="text-xs text-muted-foreground">통행료 + 예상 유류비</span></div>
    <div className="grid gap-3 md:grid-cols-3">{journey.routes.map(r=>{const selected=r.id===route.id;const eligible=r.duration-fastest.duration<=prefs.maxDetour;return <button key={r.id} onClick={()=>{update({routeId:r.id,progress:0});if(!eligible)notify('우회 허용시간을 초과하는 예시 경로입니다.')}} aria-pressed={selected} className={cn('rounded-xl border bg-card p-4 text-left shadow-sm transition-all hover:border-slate-400',selected?'route-selected':'border-border')}>
     <div className="mb-4 flex items-center justify-between gap-2"><Badge variant={selected?'default':'secondary'}>{routeLabels[r.type]}</Badge>{selected?<Check className="size-4"/>:<ChevronRight className="size-4 text-muted-foreground"/>}</div>
     <h3 className="mb-1 font-bold">{r.label}</h3><p className="mb-4 text-xs text-muted-foreground">{r.road}</p>
     <p className="text-2xl font-bold tabular-nums">{travelTime(r.duration)}</p><p className="mt-1 text-xs text-muted-foreground">{km(r.distance)} · 휴게소 {r.stops.length}곳</p>
     <div className="mt-4 flex items-center justify-between border-t border-border pt-3"><span className="text-xs text-muted-foreground">예상 이동비</span><strong className="text-base tabular-nums">{krw(cost(r))}</strong></div>
     {r.type!=='fast'&&<p className="mt-2 text-[11px] text-muted-foreground">빠른 길 대비 +{r.duration-fastest.duration}분 {eligible?'':'· 우회 설정 초과'}</p>}
    </button>})}</div></section>
   <div className="mb-10 grid gap-4 lg:grid-cols-[1.2fr_.8fr]">
     <Card className="overflow-hidden"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Route className="size-4"/> 선택한 경로</CardTitle><p className="text-xs text-muted-foreground">{route.road} · 실제 지도 정보가 아닌 개념도</p></CardHeader><CardContent><div className="map-concept relative flex min-h-[220px] flex-col justify-between rounded-lg border p-5"><div className="relative z-10 flex items-center justify-between"><Badge variant="outline" className="bg-white">{journey.from}</Badge><Badge variant="outline" className="bg-white">{journey.to}</Badge></div><svg viewBox="0 0 560 130" role="img" aria-label="경로 개념도" className="absolute inset-0 top-12 h-[145px] w-full"><path d="M 25 110 C 110 100 105 25 200 50 S 310 112 370 55 S 465 5 535 25" fill="none" stroke="#dce2e8" strokeWidth="13" strokeLinecap="round"/><path d="M 25 110 C 110 100 105 25 200 50 S 310 112 370 55 S 465 5 535 25" fill="none" stroke="#44576a" strokeWidth="4" strokeLinecap="round" strokeDasharray="1 1"/>{allStops.map((stop,i)=><circle key={stop.id} cx={80+i*(400/Math.max(allStops.length-1,1))} cy={i%2===0?80:45} r="7" fill="white" stroke="#44576a" strokeWidth="3"/>)}</svg><div className="relative z-10 flex items-center justify-between"><span className="text-xs text-muted-foreground">출발</span><span className="rounded-md bg-white px-2 py-1 text-[11px] text-muted-foreground">시연용 경로</span><span className="text-xs text-muted-foreground">도착</span></div></div></CardContent></Card>
     <Card><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-base"><Gauge className="size-4"/> 이동비용 예상</CardTitle><p className="text-xs text-muted-foreground">차량 설정에 따라 유류비가 변경됩니다</p></CardHeader><CardContent><div className="space-y-4"><div className="flex justify-between text-sm"><span className="text-muted-foreground">통행료</span><strong>{krw(route.toll)}</strong></div><div className="flex justify-between text-sm"><span className="text-muted-foreground">유류비 · {fuels[prefs.fuel]}</span><strong>{krw(fuelCost(route))}</strong></div><div className="soft-divider flex items-end justify-between pt-4"><span className="text-sm font-semibold">예상 주행비용</span><strong className="text-3xl font-bold tracking-tighter tabular-nums">{krw(cost(route))}</strong></div><Button variant="outline" className="w-full" onClick={()=>setSettingsOpen(true)}><Settings2/> 차량 연비·유가 설정</Button></div></CardContent></Card>
   </div>
   <section aria-labelledby="stops-title"><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="subhead mb-1">REST STOPS</p><h2 id="stops-title" className="text-lg font-bold">이 길에서 쉬어갈 곳 <span className="font-normal text-muted-foreground">{matchingStops.length}</span></h2></div><div className="w-full sm:w-[230px]"><Input placeholder="음식·휴게소 검색" value={foodSearch} onChange={e=>setFoodSearch(e.target.value)} aria-label="음식과 휴게소 검색"/></div></div>
   <div className="mb-4 flex flex-wrap items-center gap-2">{catNames.map(cat=><Button size="sm" key={cat} variant={prefs.category===cat?'default':'outline'} onClick={()=>update({category:cat})}>{cat}</Button>)}<Button variant={favOnly?'secondary':'ghost'} size="sm" onClick={()=>setFavOnly(x=>!x)}><Heart className={cn(favOnly&&'fill-current')}/> 즐겨찾기</Button></div>
   <div className="mb-5 flex flex-wrap gap-2">{facilities.map(f=><button key={f} aria-pressed={prefs.facilities.includes(f)} onClick={()=>toggleFacility(f)} className={cn('rounded-lg border border-border bg-white px-3 py-2 text-xs transition-colors',prefs.facilities.includes(f)&&'chip-selected')}>{icons[f]} {facilitySymbols[f]}</button>)}</div>
   {matchingStops.length?<div className="grid gap-3 md:grid-cols-2">{matchingStops.map(stop=><StopCard key={stop.id} stop={stop} favorite={prefs.favorites.includes(stop.id)} onFav={()=>toggleFavorite(stop.id)} onDetail={()=>setSelectedStop(stop.id)}/>)}</div>:<Card><CardContent className="py-12 text-center"><Info className="mx-auto mb-3 size-6 text-muted-foreground"/><p className="font-medium">조건에 맞는 휴게소가 없습니다.</p><p className="mt-1 text-sm text-muted-foreground">필터나 음식 검색어를 변경해 보세요.</p><Button size="sm" variant="outline" className="mt-4" onClick={()=>{update({category:'전체',facilities:[]});setFoodSearch('');setFavOnly(false)}}>필터 초기화</Button></CardContent></Card>}
   </section>
   <div className="mt-8 rounded-xl border bg-white p-5 md:flex md:items-center md:justify-between"><div><strong className="text-base">이동 중에도, 다음 휴게소만 간편하게.</strong><p className="mt-1 text-sm text-muted-foreground">단순한 화면으로 남은 거리와 주요 편의시설을 확인하세요.</p></div><Button className="mt-4 w-full md:mt-0 md:w-auto" onClick={()=>{setMode('drive');window.scrollTo(0,0)}}><Navigation2/> 주행 모드 열기 <ArrowRight/></Button></div>
  </main>:<main className="content-width max-w-[820px] pt-7 md:pt-10">
   <div className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><p className="subhead mb-2">ON THE ROAD · SIMULATION</p><h1 className="text-2xl font-bold">다음 휴게소</h1><p className="mt-1 text-sm text-muted-foreground">{journey.from} → {journey.to} · {route.road}</p></div><Button variant="outline" onClick={()=>setMode('plan')}><ArrowLeft/> 경로 비교</Button></div>
   <div className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900"><ShieldAlert className="mr-1 inline size-4"/> 시연용 거리입니다. GPS와 휴게소 거리는 연결되어 있지 않습니다. 운전 중 직접 조작하지 마세요.</div>
   <div className="drive-dark overflow-hidden"><div className="px-5 pb-6 pt-8 text-center"><p className="text-sm text-slate-200">{next?'다음 휴게소까지':'남은 휴게소가 없습니다'}</p><div className="big-number my-4 text-[76px] font-bold leading-none sm:text-[108px]">{next?Math.round(Math.max(0,next.km-prefs.progress)):0}<span className="ml-2 text-2xl font-medium text-slate-300">km</span></div><h2 className="text-xl font-semibold">{next?.name??'휴게소 안내 종료'}</h2><p className="mt-2 text-xs text-slate-300">{next?.road??'도착까지 안전하게 이동하세요'} · 가상 속도 90km/h 기준 약 {next?Math.ceil((next.km-prefs.progress)/90*60):0}분</p></div>
    {next&&<div className="border-t border-white/15 bg-white/5 px-5 py-5"><p className="mb-2 text-xs font-medium text-slate-300">대표 먹거리</p><div className="mb-4 flex flex-wrap gap-2">{next.foods.map(f=><span key={f.name} className="rounded-md bg-white/15 px-2.5 py-1.5 text-sm">{f.name}</span>)}</div><div className="flex flex-wrap gap-2 text-xs text-slate-200">{next.facilities.map(f=><span key={f}>{icons[f]} {facilitySymbols[f]}</span>)}</div><div className="mt-5 grid grid-cols-2 gap-2"><Button className="bg-white text-slate-900 hover:bg-slate-100" onClick={voice}><Volume2/> 음성 안내</Button><Button className="border-white/30 bg-white/10 text-white hover:bg-white/20" onClick={()=>setSelectedStop(next.id)}>상세 정보 <ChevronRight/></Button></div></div>}
   </div>
   <Card className="mt-4"><CardHeader className="pb-2"><CardTitle className="text-sm">이동 거리 시뮬레이터</CardTitle><p className="text-xs text-muted-foreground">실제 주행거리와 무관하게 화면 전환을 시험할 수 있습니다.</p></CardHeader><CardContent><input aria-label="가상 이동 거리" type="range" className="w-full accent-slate-700" min="0" max={route.distance} value={prefs.progress} onChange={e=>update({progress:Number(e.target.value)})}/><div className="mb-3 flex justify-between text-xs text-muted-foreground"><span>출발</span><span>{km(prefs.progress)} / {km(route.distance)}</span><span>도착</span></div><div className="grid grid-cols-2 gap-2"><Button variant="outline" onClick={()=>update({progress:Math.max(0,prefs.progress-20)})}>−20km</Button><Button variant="secondary" onClick={()=>update({progress:Math.min(route.distance,prefs.progress+20)})}>+20km 이동</Button></div></CardContent></Card>
   <Card className="mt-4"><CardContent className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><p className="text-sm font-semibold"><LocateFixed className="mr-1 inline size-4"/> 실제 위치 확인</p><p className="mt-1 break-all text-xs text-muted-foreground">{gps?`${gps.lat.toFixed(5)}, ${gps.lon.toFixed(5)} (오차 ±${Math.round(gps.accuracy)}m)`:(gpsError||'위치 확인 전 · 경로 탐색에는 사용되지 않음')}</p></div><Button size="sm" variant="outline" onClick={toggleGps}>{gpsOn?'위치 끄기':'GPS 켜기'}</Button></CardContent></Card>
   <h2 className="mb-3 mt-8 text-base font-semibold">그다음 휴게소</h2><div className="grid gap-3 md:grid-cols-2">{pending.slice(1).map(stop=><StopCard key={stop.id} stop={stop} favorite={prefs.favorites.includes(stop.id)} onFav={()=>toggleFavorite(stop.id)} onDetail={()=>setSelectedStop(stop.id)} remaining={stop.km-prefs.progress}/>)}</div>{pending.length<2&&<p className="py-5 text-sm text-muted-foreground">표시할 다음 휴게소가 없습니다.</p>}
  </main>}
  <footer className="content-width mt-12 border-t border-border pt-5 text-xs leading-6 text-muted-foreground"><span className="font-semibold text-foreground">쉼표 RESTWAY</span><span className="ml-3">0.2.0 · 개발 프리뷰</span><p>경로·휴게소·메뉴·가격·요금은 가상 데이터입니다. 실제 주행이나 길안내에 사용하지 마세요.</p></footer>
  <div className="mobile-stick md:hidden"><div className="mx-auto flex max-w-xl items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{mode==='plan'?`선택 경로 ${travelTime(route.duration)} · ${krw(cost(route))}`:`${next?.name??'남은 휴게소 없음'}`}</span><Button size="sm" onClick={()=>{setMode(mode==='plan'?'drive':'plan');window.scrollTo(0,0)}}>{mode==='plan'?'주행 모드':'경로 보기'} <ArrowRight/></Button></div></div>
  <Dialog open={Boolean(detail)} onOpenChange={open=>{if(!open)setSelectedStop(null)}}><DialogContent>{detail&&<><DialogHeader><DialogTitle className="text-xl font-bold">{detail.name}</DialogTitle><DialogDescription>{detail.road} · {detail.direction} · 출발 후 {km(detail.km)}</DialogDescription></DialogHeader><div><h3 className="mb-2 text-sm font-semibold">먹거리 메뉴</h3>{detail.foods.map(f=><div key={f.name} className="flex justify-between gap-3 border-b border-border py-3 text-sm"><span>{f.name}<small className="ml-2 text-muted-foreground">{f.category}</small></span><strong>{krw(f.price)}</strong></div>)}</div><div className="mt-5"><h3 className="mb-2 text-sm font-semibold">편의시설</h3><div className="flex flex-wrap gap-2">{detail.facilities.map(f=><Badge variant="secondary" key={f}>{icons[f]} {facilitySymbols[f]}</Badge>)}</div></div><p className="mt-5 rounded-md bg-secondary p-3 text-xs leading-5 text-muted-foreground">시연용 휴게소와 메뉴입니다. 실제 영업·진입가능 여부가 검증되지 않아 내비게이션 연결은 제공하지 않습니다.</p><Button className="mt-4 w-full" onClick={()=>setSelectedStop(null)}>확인</Button></>}</DialogContent></Dialog>
  <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent><DialogHeader><DialogTitle className="text-xl font-bold">차량 및 추천 설정</DialogTitle><DialogDescription>연비와 단가를 기준으로 경로별 예상비용을 계산합니다.</DialogDescription></DialogHeader><div className="space-y-4">
   <label className="block"><span className="mb-1.5 block text-sm font-medium">연료 유형</span><select className="h-10 w-full rounded-md border border-input bg-white px-3 text-sm" value={prefs.fuel} onChange={e=>{const fuel=e.target.value as FuelType;update({fuel,unitPrice:fuel==='electric'?320:fuel==='diesel'?1550:fuel==='lpg'?1020:1700,mileage:fuel==='electric'?5:prefs.mileage})}}>{Object.entries(fuels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>
   <label className="block"><span className="mb-1.5 block text-sm font-medium">공인/실연비 (km/{prefs.fuel==='electric'?'kWh':'L'})</span><Input type="number" inputMode="decimal" min="0.1" max="100" step="0.1" value={prefs.mileage} onChange={e=>update({mileage:Math.max(0.1,Number(e.target.value)||0.1)})}/></label>
   <label className="block"><span className="mb-1.5 block text-sm font-medium">유류·충전 단가 (원/{prefs.fuel==='electric'?'kWh':'L'})</span><Input type="number" inputMode="numeric" min="0" max="10000" step="10" value={prefs.unitPrice} onChange={e=>update({unitPrice:Math.max(0,Number(e.target.value)||0)})}/></label>
   <label className="block"><span className="mb-1.5 block text-sm font-medium">허용 우회 시간</span><select className="h-10 w-full rounded-md border border-input bg-white px-3 text-sm" value={prefs.maxDetour} onChange={e=>update({maxDetour:Number(e.target.value)})}>{[10,20,40,60,90].map(x=><option key={x} value={x}>{x}분</option>)}</select></label>
   <p className="rounded-md bg-secondary p-3 text-xs leading-5 text-muted-foreground">통행료는 가상 데이터입니다. 예상 유류비 = 주행거리 ÷ 입력 연비 × 입력 단가이며 실제 교통상황·할인·정차비용은 반영하지 않습니다.</p><Button className="w-full" onClick={()=>setSettingsOpen(false)}>설정 완료</Button>
  </div></DialogContent></Dialog>
  {notice&&<div role="status" aria-live="polite" className="fixed bottom-24 left-1/2 z-[100] w-max max-w-[calc(100vw-24px)] -translate-x-1/2 rounded-lg bg-slate-900 px-4 py-3 text-center text-xs leading-5 text-white shadow-xl md:bottom-8">{notice}</div>}
 </div>
}
function StopCard({stop,favorite,onFav,onDetail,remaining}: {stop:Stop,favorite:boolean,onFav:()=>void,onDetail:()=>void,remaining?:number}) {return <Card className="transition-colors hover:border-slate-300"><CardContent className="p-4 md:p-5"><div className="flex items-start justify-between gap-2"><div><div className="mb-2 flex flex-wrap items-center gap-2"><Badge variant="secondary">{stop.direction}</Badge><span className="text-xs text-muted-foreground">{stop.road}</span></div><h3 className="text-base font-bold">{stop.name}</h3><p className="mt-1 text-xs text-muted-foreground">{stop.note}</p></div><Button size="icon" variant="ghost" aria-label={favorite?'즐겨찾기 해제':'즐겨찾기 추가'} aria-pressed={favorite} onClick={onFav}><Bookmark className={cn(favorite?'fill-slate-800 text-slate-800':'text-muted-foreground')}/></Button></div><div className="my-4 flex items-center justify-between border-y border-border py-3"><div><span className="block text-xs text-muted-foreground">{remaining===undefined?'출발지 기준':'현재 진행거리 기준'}</span><span className="text-lg font-bold tabular-nums">{km(remaining??stop.km)}</span></div><div className="flex gap-1.5">{stop.facilities.slice(0,3).map(f=><span key={f} title={facilitySymbols[f]} className="rounded-md bg-secondary px-2 py-1 text-[11px]">{icons[f]} {facilitySymbols[f]}</span>)}</div></div><div className="flex flex-wrap gap-1.5">{stop.foods.filter(f=>f.highlight).concat(stop.foods.filter(f=>!f.highlight)).slice(0,3).map(f=><span key={f.name} className="rounded-md border border-border px-2 py-1 text-xs text-foreground">{f.name}</span>)}</div><Button variant="outline" size="sm" className="mt-4 w-full" onClick={onDetail}>메뉴·편의시설 보기 <ChevronRight/></Button></CardContent></Card>}
